name: CI
on:
    push:
        branches: [master, dev, quality]
    pull_request:
        branches: [master, dev, quality]

jobs:
    verify_files:
        name: Mocha Tests
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: '14.x'
            - name: Install Packages
              run: npm install
            - name: Run Mocha Tests
              run: npm run test
            - name: Send JavaScript Coverage to Codacy
              run: bash <(curl -Ls https://coverage.codacy.com/get.sh) report -l Javascript -r coverage.lcov
            - name: Send TypeScript Coverage to Codacy
              run: bash <(curl -Ls https://coverage.codacy.com/get.sh) report -l TypeScript -r coverage.lcov
